---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2021/11/8 11:23 上午
---

wrk.method = "POST"
wrk.headers["Content-Type"] = "application/json"
local uid = 1007 --- 根据数据库情况设置，
function request()
    local body = '{"uid":%s}'
    body = string.format(body, uid)
    uid = uid + 1
    return wrk.format(nil, nil, nil, body)
end
