---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by apple.
--- DateTime: 2021/11/8 11:23 上午
local json = require "json"

wrk.method = "POST"
wrk.headers["Content-Type"] = "application/json"
local uid = 1 --- 根据数据库情况设置，
local envelope_id = 0
local path = "/redenvelope/snatch"
local body = '{"uid": 1}'
local data = ""

function request()
    --- 只有当上一个请求为抢红包并且拿到的data不为空时才发送拆红包请求
    if (path == "/redenvelope/snatch") then
        if (data ~= nil) then
            ---print("open", data["envelope_id"])
            envelope_id = data["envelope_id"]
            path = "/redenvelope/open"
            body = '{"uid":%s,"envelope_id":%s}'
            body = string.format(body, uid, envelope_id)
        else
            ---print("data==nil")
            body = '{"uid":%s}'
            uid = uid + 1
            body = string.format(body, uid)
            path = "/redenvelope/snatch"
        end
    else
        ---print("snatch")
        body = '{"uid":%s}'
        uid = uid + 1
        body = string.format(body, uid)
        path = "/redenvelope/snatch"
    end
    ---print(body, path)
    return wrk.format(nil, path, nil, body)
end

function response(status, headers, body)
    local res = json.decode(body)
    data = res["data"]
end