server:
  port: 8080
database:
  driverName: mysql
  userName: developer
  password: Group1234.
  host: 111.62.122.65
  database: red_envelope_rain
  #空闲时的最大连接数
  MaxOpenConns: 100
  #与数据库的最大连接数
  MaxIdleConns: 100
  #每个连接的生命周期 单位秒
  ConnMaxLifeTime: 300
redis:
  addr: redis-cn02jdaqbqmj56pxs.redis.volces.com:6379
  username: developer
  password: Group1234.
  dbNumber: 0

# 下面的还有没有用？是否应该跟redis做联动？
snatchProbability: 70
snatchMaxCount: 5
totalNum: 100
#金额单位: 分
totalAmount: 100000
minAmount: 100
maxAmount: 3000
#限制器
#每秒放入的令牌数量
limitRate: 1000
#桶容量
limitCapacity: 1000
